### ISSUE TITLE
建议在仓库中直接上传源文件

### ISSUE THREAD

**Issue by cognition9144** [Bambooin/rimerc#1]
建议在仓库中直接上传源文件而不是压缩包，既然已经用 Apache 协议，并且被输入法项目推荐了。这样在输入法那里也许可以争取加为默认配置，像 KDE 的「Simple by default, powerful when needed」哲学，对使用者而言体验会更好。

另外，分 branches 来维护对不同平台大部分是相同配置的项目来说也比较好。

**Comment by Bambooin** [comment]
源文件太大，不利于下载，尤其 Github 的下载速度。

为压缩前大概22M，其中几个大的词库为。
~/.config/fcitx/rime
 12M luna_pinyin.sgmain.dict.yaml
2.0M luna_pinyin.sgplus2.dict.yaml
1.7M luna_pinyin.hanyu.dict.yaml
1.1M luna_pinyin.history.dict.yaml

压缩后
8.2M weasel.7z
7.2M squirrel.7z
6.7M trime.7z

**Comment by Bambooin** [comment]
并不是输入法推荐，是我看到好多新手使用Trime报错，才提得PR

可以建议 osfans 设置默认，以前和他提过，不过这个词库还是有些大，输入方案太单一，不太适合

**Comment by Bambooin** [comment]
可以使用 公共文件夹，放置共同部分，是个好主意，以前考虑过

PS: 目前也在使用 KDE 推荐使用 fcitx + rime，配置文件按照文档，效果很好，我日常使用没问题

**Comment by cognition9144** [comment]
GitHub Releases 是用作存放打包好的成品的，把压缩包放那里更合适，并不矛盾

**Comment by Bambooin** [comment]
分开放置是个好方向，一些公共文件，特殊配置文件单独放置，写个脚本打包到release

**Comment by Bambooin** [comment]
已经实现打包配置功能
