### ISSUE TITLE
【功能建议】添加输入法横排显示功能 & 拼写 'date' 可输出当前日期

### ISSUE THREAD

**Issue by xielh96** [Bambooin/rimerc#10]
平台：ibus
1. 默认没有配置横排/垂直显示设置，建议添加。
2. 拼写 'date' 可输出当前日期。
3. 拼写 'time' 可输出当前时间。

感谢大佬提供的配置，开箱即用，辛苦了。👨‍💻

**Comment by Bambooin** [comment]
1: fcitx5 可以在图形话页面设置
2 & 3: 应该可以使用 Lua 脚本实现

PS: Linux 平台的话，建议使用 fcitx5
