### ISSUE TITLE
[Trime] Chinese/English toggle state for Luna is not persisted

### ISSUE THREAD

**Issue by dogtopus** [Bambooin/rimerc#11]
After updating to the latest release, the state of Chinese/English toggle for Luna Pinyin is no longer persisted and defaults to Chinese every time the input focus is changed. This gets annoying when I need to type in English in a specific chat or even filling a form in English. A workaround is to just use the system keyboard for English but I think it's not as convenient as using the toggle.

更新到最新版之后，中英文切换按钮的状态在文本框锁定改变的情况下会丢失，变回中文。在某些需要相对连续输入英文的情况下需要不停切换中英文状态，比较麻烦。

**Comment by Bambooin** [comment]
see https://github.com/osfans/trime/issues/643

Waiting for it to be fixed

**Comment by dogtopus** [comment]
Oh yeah I updated Trime too recently so it might actually be a Trime issue all along. Thanks for pointing it out.
