### ISSUE TITLE
如果要在超强二笔词典上新增词汇（如自己工作常用词汇或专有词汇），能否参照用上rimerc中的配置方法？

### ISSUE THREAD

**Issue by happypxw** [Bambooin/rimerc#3]
如题，似乎rimerc中的配置方法只适用于音码表

**Comment by Bambooin** [comment]
rimerc 里面的配置是**明月拼音**，你的输入方案确实和这个不同，如需使用可能需要，转换词典。

**Comment by Bambooin** [comment]
还有可以把自己的配置备份，使用 rimerc 试试，看看使用拼音输入是否流畅和习惯。

**Comment by happypxw** [comment]
已搜到一个好的配置（whjiang/cqeb），里面有我想要的自组词汇方法（就是键盘翻页键与词汇键有点小冲突，已解决），还是谢谢大佬百忙之中答复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Bambooin/rimerc"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月11日(星期一) 上午10:03
收件人:&nbsp;"Bambooin/rimerc"<rimerc@noreply.github.com&gt;;
抄送:&nbsp;""<happypxw@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Bambooin/rimerc] 如果要在超强二笔词典上新增词汇（如自己工作常用词汇或专有词汇），能否参照用上rimerc中的配置方法？ (#3)





 
rimerc 里面的配置是明月拼音，你的输入方案确实和这个不同，如需使用可能需要，转换词典。
