### ISSUE TITLE
试了trime.7z不能输出简体中文, 只能繁体输出

### ISSUE THREAD

**Issue by hlizard** [Bambooin/rimerc#4]
如题, 有简繁切换选项但无效, 下载的是Trime最新测试版, 手机是华为, Android 10

**Comment by Bambooin** [comment]
应该是 opencc 没有导致的，尝试在 设置->恢复默认设置->勾选 opencc->然后重新部署

**Comment by hlizard** [comment]
嗯, 照你说的操作后可以输入简体字了, 而且自己添加的几个输入方案现在这正常了, 之前用不了, 多谢!

**Comment by iT-Boyer** [comment]
安裝rimerc之後，在**default_custom_comfig.yaml**配置lunal_pinyin_simp方案
```
1 customization:
   2   distribution_code_name: ""
   3   distribution_version: ""
   4   generator: "Rime::SwitherSettings"
   5   modified_time: "Sun Jun 20 00:03:45 2021"
   6   rime_version: 1.5.3
   7 patch:
   8   schema_list:
   9     - {schema: easy_en}
  10     - {schema: luna_pinyin}
          - {schema: luna_pinyin_simp}
```
只有英文和繁體兩種方案
@Bambooin 
按照重置opencc的方法，再重置其他文件

**Comment by czhang03** [comment]
我也有类似问题

- rimerc version: `rimerc-trime-0.1.6.zip`
- trime version: `v3.2.11` from f-droid
- Android version: 13
- Step produced:
  - delete the `build` folder from `~/rime/build`
  - clean cache for `trime`
  - reset in `setting -> profile -> reset`, and select all three
  - rebuild by clicking `deploy`

之后仍然无法切换繁简输入法
