### ISSUE TITLE
trime.7z中有sougou，但在输入方案中没有显示，需要怎么配置？

### ISSUE THREAD

**Issue by yichuang-zh** [Bambooin/rimerc#5]
trime.7z中有sougou，但在输入方案中没有显示，需要怎么配置？
我用的安卓手机。

**Comment by Bambooin** [comment]
如果是指 luna_pinyin.sgmain.dict.yaml 搜狗词库的话，配置文件默认已经添加这个词库。

如果是指 sougou.trime.yaml 的话，这个是搜狗主题，在 键盘->主题 里面可选，
但是建议使用 tongwenfeng.trime.yaml 主题，功能更齐全， sougou.trime.yaml 主题上游已经不维护了。

**Comment by ameaninglessname** [comment]
> 如果是指 sougou.trime.yaml 的话，这个是搜狗主题，在 键盘->主题 里面可选


对,但选了用不了

**Comment by Bambooin** [comment]
不同主题的键盘布局不一样，在设置里面，点击 键盘->主题->选择 sougou ->点击确定，就切换到搜狗主题了

sougou.trime.yaml 的配色只有一种，tongwenfeng.trime.yaml 配色有很多，可以验证一下

**Comment by Bambooin** [comment]
刚才验证了一下，可以使用 sougou.trime.yaml 主题
